# Generated by Django 4.2.25 on 2026-01-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_coment_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='item_name',
            field=models.CharField(default='americano', max_length=100),
        ),
    ]
