# Generated by Django 4.2.25 on 2026-01-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coment_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='item_name',
        ),
    ]
