# Generated by Django 4.2.25 on 2026-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_coment_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='menuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=False)),
                ('icon', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='coment',
        ),
    ]
