# Generated by Django 4.2.25 on 2026-01-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_com_menuu_delete_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.menuu'),
            preserve_default=False,
        ),
    ]
