from django.urls import path
from myapp import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.start_page, name='start'),  # головна перевірка
    path('main/', views.main, name='main'),
    path('menu/', views.menu, name='menu'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('breakfest/', views.breakfest, name='breakfest'),
    path('salat/', views.salat, name='salat'),
    path('sup/', views.sup, name='sup'),
    path('drink/', views.drink, name='drink'),
    path('desert/', views.desert, name='desert'),
    path('desert/moroz/', views.moroz, name='moroz'),
    path('desert/morozcom/', views.morozcom, name='morozcom'),
    path('desert/nap/', views.nap, name='nap'),
    path('desert/napcom/', views.napcom, name='napcom'),
    path('desert/tir/', views.tir, name='tir'),
    path('desert/tircom/', views.tircom, name='tircom'),
    path('ohibka/', views.ohibka, name='ohibka'),
    path('sirniku/', views.sirniku, name='sirniku'),
    path('tostu/', views.tostu, name='tostu'),
    path('vafli/', views.vafli, name='vafli'),
    path('sirniku/mal/', views.sirniku_mal, name='mal'),
    path('sirniku/shok/', views.sirniku_shok, name='shok'),
    path('sirniku/sol/', views.sirniku_sol, name='sol'),
    path('tostu/avo/', views.tostu_avo, name='avo'),
    path('tostu/chdj/', views.tostu_chdj, name='chdj'),
    path('tostu/maldj/', views.tostu_maldj, name='maldj'),
    path('tostu/poldj/', views.tostu_poldj, name='poldj'),
    path('tostu/sur/', views.tostu_sur, name='sur'),
    path('vafli/maldjm/', views.vafli_maldjm, name='maldjm'),
    path('vafli/med/', views.vafli_med, name='med'),
    path('vafli/poldjm/', views.vafli_poldjm, name='poldjm'),
    path('vafli/sirop/', views.vafli_sirop, name='sirop'),
    path('voda/', views.voda, name='voda'),
    path('tea/', views.tea, name='tea'),
    path('smyzi/', views.smyzi, name='smyzi'),
    path('kok/', views.kok, name='kok'),
    path('kava/', views.kava, name='kava'),
    path('espresso/', views.espresso, name='espresso'),
    path('espressocom/', views.espressocom, name='espressocom'),
    path('americano/', views.americano, name='americano'),
    path('americanocom/', views.americanocom, name='americanocom'),    
    path('kapuchino/', views.kapuchino, name='kapuchino'),
    path('kapuchinocom/', views.kapuchinocom, name='kapuchinocom'),
    path('latte/', views.latte, name='latte'),
    path('lattecom/', views.lattecom, name='lattecom'),
    path('kakao/', views.kakao, name='kakao'),
    path('kakaocom/', views.kakaocom, name='kakaocom'),
    path('mol/', views.mol, name='mol'),
    path('molcom/', views.molcom, name='molcom'),
    path('blla/', views.blla, name='blla'),
    path('bllacom/', views.bllacom, name='bllacom'),
    path('mohito/', views.mohito, name='mohito'),
    path('mohitocom/', views.mohitocom, name='mohitocom'),  
    path('cherry/', views.cherry, name='cherry'),
    path('cherrycom/', views.cherrycom, name='cherrycom'),
    path('polynisa/', views.polynisa, name='polynisa'),
    path('polynisacom/', views.polynisacom, name='polynisacom'),
    path('banan/', views.banan, name='banan'),
    path('banancom/', views.banancom, name='banancom'),
    path('green/', views.green, name='green'),
    path('greencom/', views.greencom, name='greencom'),
    path('black/', views.black, name='black'),
    path('blackcom/', views.blackcom, name='blackcom'),
    path('1001night/', views.night, name='night'),
    path('1001nightcom/', views.nightcom, name='nightcom'),
    path('sik/', views.sik, name='sik'),
    path('sikcom/', views.sikcom, name='sikcom'),
    path('sprite/', views.sprite, name='sprite'),
    path('spritecom/', views.spritecom, name='spritecom'),  
    path('kola/', views.kola, name='kola'),
    path('kolacom/', views.kolacom, name='kolacom'),
    path('yzvar/', views.yzvar, name='yzvar'),
    path('yzvarcom/', views.yzvarcom, name='yzvarcom'),
    path('grech/', views.grech, name='grech'),
    path('krevetka/', views.krevetka, name='krevetka'),
    path('salat/ol/', views.ol, name='ol'),
    path('salat/shezar/', views.shezar, name='shezar'),
    path('salat/zavok/', views.zavok, name='zavok'),
    path('salat/avokado/', views.avokado, name='avokado'),
    path('sup/frik/', views.frik, name='frik'),
    path('sup/bul/', views.bul, name='bul'),
    path('sup/borch/', views.borch, name='borch'),
    path('sup/zelborch/', views.zelborch, name='zelborch'),
]   




 